package:
  name: facs
  version: 0.1
  
source:
  git_url: https://github.com/HiramHe/FACS.git

build:
  number: 0

requirements:
  build:
  run:
    - eXpress

about:
  summary: "a module for amp prediction"